### ISSUE TITLE
Set new Global ENV

### ISSUE THREAD

**Issue by DarkDrim** [antonybudianto/angular2-starter#100]
## Global.env param
Hello! How can I add an additional parameter to global.env ?
There are four modes of operation: dev (local), testing, productrion, and demo.
How can I add a "demo"?
I run: gulp build --env=demo
But it does not work.

PS I want in file main.ts present variable "declare var ENV: string" // demo

**Comment by antonybudianto** [comment]
env for gulp tasks should be using `--env=demo`

but for build step, it's in
https://github.com/antonybudianto/angular2-starter/blob/master/src/systemjs.conf.js#L9

**Comment by DarkDrim** [comment]
I run gulp serve-dev --env=demo
But in systemjs.conf file global.ENV == undefined

**Comment by antonybudianto** [comment]
no, --env=demo will never affect global.ENV since they're totally different.
--env is for node environment, global.ENV is for browser environment

**Comment by DarkDrim** [comment]
Yes, how i can change global.ENV?
I want add "global.ENV = demo". How I can do this?

**Comment by antonybudianto** [comment]
you can declare that anywhere before systemjs.conf.js loaded, for example you create env.js with following lines:
```js
(function(global){
global.ENV = 'demo';
})(window);
```
and load the script before systemjs.conf.js

**Comment by DarkDrim** [comment]
I have a different configuration files (a class).
I depending on the environment variable must use different files.
For example, "demo.conf" or "dev.conf"

**Comment by DarkDrim** [comment]
Thank you, it solved my problem.
