### ISSUE TITLE
IDE breakpoint debugging

### ISSUE THREAD

**Issue by antonybudianto7** [antonybudianto/angular2-starter#102]
Currently we can do in-browser breakpoint successfully
![tes3](https://cloud.githubusercontent.com/assets/14085717/16104846/f551675a-33ae-11e6-8bb4-a8401df0a944.png)

But we can't do it in IDEs

**Comment by antonybudianto7** [comment]
From this https://www.youtube.com/watch?v=RQSRKi3VZ3I, looks like the IDE needs to implement the extension for the browser

**Comment by antonybudianto7** [comment]
For Visual Studio Code
https://dzone.com/articles/completing-the-angular-2-quick-start-in-vs-code-1

**Comment by antonybudianto** [comment]
closing because not actionable/need effort on IDE side
