### ISSUE TITLE
E2E-testing and socket.io-client

### ISSUE THREAD

**Issue by DarkDrim** [antonybudianto/angular2-starter#109]
Hello! There was another problem. When I connect socket.io-client application in Angular2 e2e-tests do not work: the browser is started and the hanging for 30 seconds, and then terminates. But the e2e-tests did not pass.
Unit tests are working well.

Socket.io-client I connect like this:
in System.js (map):
`'socket.io-client': 'n:socket.io-client'`
packages:
`'socket.io-client': {
            defaultExtension: 'js',
            main: 'socket.io.js',
            format: 'cjs'
        }`

In services:
`import * as io from 'socket.io-client';`

and use like this:
`io.connect(...)`

I starting gulp. Then gulp e2e.
What should be done to e2e tests have started?

**Comment by antonybudianto** [comment]
Is it working without socket.io ?

**Comment by DarkDrim** [comment]
Yes

**Comment by antonybudianto** [comment]
Maybe related to port ?

**Comment by antonybudianto** [comment]
Also I need the error traces

**Comment by DarkDrim** [comment]
Connect:
`this.socket = io.connect('http://sellers.site.com');`

When you run the e2e-test no errors.
Just the browser "hangs" in 30 seconds and drop tests with the message:
`gulp e2e
...
[09:41:20] Starting 'driver-update'...
[09:41:20] Starting 'clean-ts-test'...
[09:41:20] Finished 'clean-ts-test' after 15 ms
[09:41:20] Starting 'tsc-e2e'...
selenium standalone is up to date.
chromedriver is up to date.
[09:41:20] Finished 'driver-update' after 328 ms
[09:41:22] Finished 'tsc-e2e' after 2.69 s
[09:41:22] Starting 'e2e-test'...
[09:41:22] Finished 'e2e-test' after 1.35 ms
[09:41:22] Starting 'e2e'...
[09:41:22] Finished 'e2e' after 6.29 μs
[09:41:23] I/local - Starting selenium standalone server...
[09:41:23] I/launcher - Running 1 instances of WebDriver
[09:41:24] I/local - Selenium standalone server started at http://10.5.1.53:4390
4/wd/hub
Started
FF

Failures:
1) Dashboard Home page should have title
  Message:
    Failed: Timed out waiting for Protractor to synchronize with the page after
30 seconds. Please see https://github.com/angular/protractor/blob/master/docs/fa
q.md
  Stack:
    Error: Failed: Timed out waiting for Protractor to synchronize with the page
 after 30 seconds. Please see https://github.com/angular/protractor/blob/master/
docs/faq.md
        at C:\OpenServer\domains\saveren-fe-new\fe\src\sellers\node_modules\gulp
-protractor\node_modules\protractor\node_modules\jasminewd2\index.js:101:16
        at Promise.invokeCallback_ (C:\OpenServer\domains\saveren-fe-new\fe\src\
sellers\node_modules\gulp-protractor\node_modules\protractor\node_modules\seleni
um-webdriver\lib\promise.js:1329:14)
        at TaskQueue.execute_ (C:\OpenServer\domains\saveren-fe-new\fe\src\selle
rs\node_modules\gulp-protractor\node_modules\protractor\node_modules\selenium-we
bdriver\lib\promise.js:2790:14)
        at TaskQueue.executeNext_ (C:\OpenServer\domains\saveren-fe-new\fe\src\s
ellers\node_modules\gulp-protractor\node_modules\protractor\node_modules\seleniu
m-webdriver\lib\promise.js:2773:21)

2) Dashboard Home page should have image
  Message:
    Failed: Cannot assign to read only property 'stack' of Timed out waiting for
 Protractor to synchronize with the page after 30 seconds. Please see https://gi
thub.com/angular/protractor/blob/master/docs/faq.md
    While waiting for element with locator - Locator: By(css selector, img)
  Stack:
    TypeError: Cannot assign to read only property 'stack' of Timed out waiting
for Protractor to synchronize with the page after 30 seconds. Please see https:/
/github.com/angular/protractor/blob/master/docs/faq.md
    While waiting for element with locator - Locator: By(css selector, img)
        at C:\OpenServer\domains\saveren-fe-new\fe\src\sellers\node_modules\gulp
-protractor\node_modules\protractor\built\element.js:377:21
        at Promise.invokeCallback_ (C:\OpenServer\domains\saveren-fe-new\fe\src\
sellers\node_modules\gulp-protractor\node_modules\protractor\node_modules\seleni
um-webdriver\lib\promise.js:1329:14)
        at TaskQueue.execute_ (C:\OpenServer\domains\saveren-fe-new\fe\src\selle
rs\node_modules\gulp-protractor\node_modules\protractor\node_modules\selenium-we
bdriver\lib\promise.js:2790:14)
        at TaskQueue.executeNext_ (C:\OpenServer\domains\saveren-fe-new\fe\src\s
ellers\node_modules\gulp-protractor\node_modules\protractor\node_modules\seleniu
m-webdriver\lib\promise.js:2773:21)
        at C:\OpenServer\domains\saveren-fe-new\fe\src\sellers\node_modules\gulp
-protractor\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.
js:2652:27
        at C:\OpenServer\domains\saveren-fe-new\fe\src\sellers\node_modules\gulp
-protractor\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.
js:639:7
        at process._tickCallback (node.js:369:9)
    From: Task: Run it("should have image") in control flow
        at Object.<anonymous> (C:\OpenServer\domains\saveren-fe-new\fe\src\selle
rs\node_modules\gulp-protractor\node_modules\protractor\node_modules\jasminewd2\
index.js:81:14)
    From asynchronous test:
    Error
        at Suite.<anonymous> (C:\openserver\domains\saveren-fe-new\fe\src\seller
s\src\tmp\test\e2e\dashboard-home\test\e2e\dashboard-home\dashboard-home.spec.ts
:12:5)
        at Object.<anonymous> (C:\openserver\domains\saveren-fe-new\fe\src\selle
rs\src\tmp\test\e2e\dashboard-home\test\e2e\dashboard-home\dashboard-home.spec.t
s:1:1)
        at Module._compile (module.js:409:26)
        at Object.Module._extensions..js (module.js:416:10)
        at Module.load (module.js:343:32)
        at Function.Module._load (module.js:300:12)

2 specs, 2 failures
Finished in 67.866 seconds
[09:42:34] I/local - Shutting down selenium standalone server.
[09:42:34] I/launcher - 0 instance(s) of WebDriver still running
[09:42:34] I/launcher - chrome #01 failed 2 test(s)
[09:42:34] I/launcher - overall: 2 failed spec(s)
[09:42:34] E/launcher - Process exited with error code 1
Error running E2E testing`

**Comment by antonybudianto** [comment]
do you use the latest starter?

**Comment by DarkDrim** [comment]
No, this is "Angular 2 Starter RC 2".
But now I will make the transition to the latest version.

**Comment by antonybudianto** [comment]
please post this to stackoverflow.com too because it's more appropriate to post it there than here, unless something wrong with the starter

**Comment by DarkDrim** [comment]
Soon I will give a link to the repository. And then will place a question on Stack

**Comment by antonybudianto** [comment]
Thank you

**Comment by DarkDrim** [comment]
@antonybudianto https://bitbucket.org/drimsoftware/angular2-socket.io
This repo use mercurial (not git).
For downld project: https://bitbucket.org/drimsoftware/angular2-socket.io/downloads
npm i
gulp & gulp e2e
What do you think about this?
Thanks for your answers!

**Comment by antonybudianto** [comment]
sorry looks like your repo had been modified much, no typings and all.

**Comment by DarkDrim** [comment]
Sorry. One moment

**Comment by antonybudianto** [comment]
Looks like it's not starter issue

**Comment by DarkDrim** [comment]
Likely.
Do you have reproduced the problem?

**Comment by antonybudianto** [comment]
I can't because of typings missing

**Comment by antonybudianto** [comment]
The best would be on stackoverflow

**Comment by DarkDrim** [comment]
I fix the typings.
Okay, i will write on stackoverflow
