### ISSUE TITLE
EADDRINUSE 3001

### ISSUE THREAD

**Issue by kennyhyun** [antonybudianto/angular2-starter#111]
## Issue Overview
`gulp serve-build` fails with `Error: listen EADDRINUSE :::3001`.

## Issue Description
ports looks conflict with browserSync.

## Reproducables
always. 4045662 chore(package.json): update karma stable (#110)

## Information
|                      	|                                 	|
|---------------------	|---------------------------------	|
| **Operating System** 	| Windows 10 	|
| **Node version**     	| 4.4.5   	|
| **NPM Version**      	| 2.15.5    	|
| **Environment**       | Chrome          |

**Comment by antonybudianto** [comment]
I've tried but failed to reproduce. Maybe the port is still used by another program? Can you try to restart the OS and try again? 
Thanks

**Comment by kennyhyun** [comment]
After I reboot, I went well! Thank you;)

but when I tried editing the port `3001` in `config/gulp/config.js` into `13000`, I could run it.
I could see the browserSync page from `localhost:3001`.
After rebooting, changing port to 13000 and opening http://localhost:3001 still shows browserSync.
Is it normal?

**Comment by kennyhyun** [comment]
I've checked [the browsersync docs](https://www.browsersync.io/docs/options/#option-ui), 
ui port default value is 3001.
but it moves to 3002 when the local port is 3001, without any ui port option.

    [BS] Access URLs:
     --------------------------------------
           Local: http://localhost:3001
        External: http://192.168.1.111:3001
     --------------------------------------
              UI: http://localhost:3002
     UI External: http://192.168.1.111:3002
     --------------------------------------

It's weird but it was temporary. no problem.

Have a good weekend, mate!

**Comment by antonybudianto** [comment]
Thank you, mate.

**Comment by antonybudianto** [comment]
Looks like I need to choose another non-default ports then
