### ISSUE TITLE
Chrome Sources tab not showing typescript code, so unable to debug.

### ISSUE THREAD

**Issue by kumargandhi** [antonybudianto/angular2-starter#120]
Hi,

Thank you for this starter this really helped me to understand module loader and build system. 

Issue:
When i tried to debug i only see JavaScript code in the Chrome browser but not the TypeScript code.

**Comment by antonybudianto** [comment]
<img width="723" alt="screen shot 2016-07-08 at 11 45 15 pm" src="https://cloud.githubusercontent.com/assets/7658554/16694742/1532f516-4566-11e6-9672-8b9dbb59a162.png">

**Comment by antonybudianto** [comment]
you can also debug during test, see [here](https://github.com/antonybudianto/angular2-starter/issues/101#issuecomment-226095910)

**Comment by kumargandhi** [comment]
I do not see source/app in my console and in the config file !!. 

Anyways i figured out the problem. I changed the write settings for my sourcemaps. They were not properly set. https://www.npmjs.com/package/gulp-sourcemaps

**includeContent: false, 

> sourceRoot: '../../'

**

**Comment by antonybudianto** [comment]
you didn't provide me with any reproducables so I tested it using latest starter, and the sourcemap is working. 
maybe your browser didn't support inline sourcemap yet, setting `../..` may not work on nested component

**Comment by kumargandhi** [comment]
Hi @antonybudianto ,
You are correct and i am wrong, I checked the starter again it had changes - typescript compile.
It's working.
For the record the issue was **includeContent: false**, setting it to true worked.
Does this have any impact on production build.
Thank you.

**Comment by antonybudianto** [comment]
sourcemap will not affect production build
