### ISSUE TITLE
Not sure if I missed it but how to install 3rd party dependencies? (primeng)

### ISSUE THREAD

**Issue by mthor** [antonybudianto/angular2-starter#124]
what to do with third party dependencies, do I need to register with sysytemjs, or do we just add them in the index page

**Comment by antonybudianto** [comment]
please refer to https://github.com/antonybudianto/angular2-starter/wiki/Contributing#submitting-issues

**Comment by mthor** [comment]
well, this is why your project will never compare to angular-seed2, talk about shitty experience, if you are going to make a project for others to clone or fork, you need to really learn about how to have an active issue list.  Thanks for helping me decide what to use, 
'
https://github.com/mgechev/angular2-seed  is a much better project and well maintained, also they answer issues. blows this starter project out of the water.

**Comment by antonybudianto** [comment]
@mthor, you don't give me any reproducable for your issue, then how I supposed to solve it? 
if you give me a detail and reproducable, of course I will try to solve the issue.
