### ISSUE TITLE
npm install fails under powershell

### ISSUE THREAD

**Issue by foxjazz** [antonybudianto/angular2-starter#125]
Only in windows npm install fails and npm start.

**Comment by antonybudianto7** [comment]
please give more details and some error traces

**Comment by foxjazz** [comment]
From what I can tell, it was stuck on phantom but then it just wouldn't start.
Best way to test is just to clone repo, npm install and npm start under a windows 10 environment.

**Comment by antonybudianto7** [comment]
Sorry but I didn't have windows machine, I used Mac.
Let's keep this open for now

**Comment by antonybudianto7** [comment]
Also please post the error trace @foxjazz

**Comment by antonybudianto7** [comment]
closing, and continue to #126
