### ISSUE TITLE
TsLint in gulp process

### ISSUE THREAD

**Issue by talmog** [antonybudianto/angular2-starter#13]
Thank you for this repo, it is great!

I would like to have tslint run on every ts change and log it to the console warning after every save. right now if I add 'ts-lint' to serve it errors out and will not run the server.
Could you help with that please?
Thank you!

**Comment by antonybudianto** [comment]
Hello, thanks for trying the starter!
You could add tslint to the compileTs pipe:
```javascript
function compileTs(files) {
    var res = gulp.src(files, {
            base: '.'
        })
        .pipe(tslint())
        .pipe(tslint.report('prose', {
            summarizeFailureOutput: true
        }))
...
```

**Comment by antonybudianto** [comment]
I
