### ISSUE TITLE
Support for "Component Relative Path"

### ISSUE THREAD

**Issue by manish5377** [antonybudianto/angular2-starter#135]
<GitHub issues are ONLY for BUG reports and FEATURE requests>
<Questions or support can be send to StackOverflow>
<PLEASE DO FOLLOW and fill the issue template below. Don't skip or remove any section>

## Issue Overview
Requesting support for Component Relative Path

## Issue Description
We were trying to utilize this starter and add support for https://angular.io/docs/ts/latest/cookbook/component-relative-paths.html .

However, when we build for production using "@ngstarter/systemjs-extension", html templates were not getting downloaded. All xhr request for html templates were pointing to root.

We must be missing something, hence requesting support for "Component Relative Path"

## Reproducables
Just use the starter and change "absolute url" in component to relative url. Build for production and serve.

## Information
|                      	|                                 	|
|---------------------	|---------------------------------	|
| **Operating System** 	| Windows 10	|
| **Node version**     	| 5.x   	|
| **NPM Version**      	| 3.8.x    	|
| **Environment**       | Browser         |

**Comment by antonybudianto** [comment]
For now you can try https://angular.io/docs/ts/latest/cookbook/component-relative-paths.html

**Comment by manish5377** [comment]
We did try as suggested by @antonybudianto . 

Issue we encountered for development build was that .html files were not being copied to /src/tmp folder. Once we did that it worked well for dev.

However for production build, html files are copied to /build folder however all xhr request for html templates were pointing to root. e.g. localhost:3001/abc.html

We were expecting it to be something like localhost:3001/some-comonent/abc.html (provided abc.html is template for "some-component" within "some-component" folder.

Thanks for any help you can provide.

**Comment by antonybudianto7** [comment]
I never tried that myself, maybe you can post to stackoverflow for more assistance, Sorry cannot help much

**Comment by antonybudianto7** [comment]
By the way, Angular 2 already introduces Compiler CLI which will compile the component and the template, which we don't need to care relative/absolute paths anymore, I'll try investigating that

**Comment by antonybudianto** [comment]
https://github.com/angular/angular/issues/6053#issuecomment-222341010

**Comment by manish5377** [comment]
Thanks @antonybudianto . That was very useful.

**Comment by manish5377** [comment]
One more question.
This starter is using "SystemJS" as module loader. Is it in development mode OR for Production deployment as well?

**Comment by antonybudianto** [comment]
It's for module loader, for production you can use webpack / SystemJS Builder (default)
