### ISSUE TITLE
Upgrade Angular Dependencies to RC.5

### ISSUE THREAD

**Issue by AlexLovato** [antonybudianto/angular2-starter#136]
## Issue Overview
Angular 2.0.0-rc.5 is out with some breaking changes

## Issue Description
Dependencies in this app point to rc.4. I can start the refactor and submit a PR if you would like.

## Reproducables
n/a

## Information
|         key                        |                                      val            |
|---------------------	|---------------------------------|
| **Operating System**| OSX	                                        |
| **Node version**     	| 4                                             	|
| **NPM Version**      	| 3.5.3                                       	|
| **Environment**       | Browser          |

**Comment by antonybudianto** [comment]
@AlexLovato , I've created  a PR for that, please try it if it works well, thanks!

**Comment by AlexLovato** [comment]
I got the app running, now I need to get the tests fine again, then I'll submit the PR for you to look over!
