### ISSUE TITLE
Error after removing Todolist component

### ISSUE THREAD

**Issue by oluijks** [antonybudianto/angular2-starter#138]
## Issue Overview
Added new about component and that works fine, but get an browser error after fully removing the Todo component.

## Issue Description
Removed Todo component. Updated app.module.ts, nav.html (removed link), app.routing.ts

## Reproducables
Removed Todo component. Updated app.module.ts, nav.html (removed link), app.routing.ts and all files that make a reference to the Todo component.

The error I don't seem to get rid of is (error only occurs in the browser, not in the console)

zone.js:461 Unhandled Promise rejection: No ExceptionHandler. Is platform module (BrowserModule) included? ; Zone: <root> ; Task: Promise.then ; Value: Error: No ExceptionHandler. Is platform module (BrowserModule) included?(…)consoleError @ zone.js:461_loop_1 @ zone.js:490drainMicroTaskQueue @ zone.js:494ZoneTask.invoke @ zone.js:426
zone.js:463 Error: Uncaught (in promise): Error: No ExceptionHandler. Is platform module (BrowserModule) included?(…)consoleError @ zone.js:463_loop_1 @ zone.js:490drainMicroTaskQueue @ zone.js:494ZoneTask.invoke @ zone.js:426

## Information
| **Operating System** 	| Ubuntu 	  |
| **Node version**     	| 6.3.0   	  |
| **NPM Version**      	| 3.10.5      |
| **Environment**            | Browser   |

**Comment by antonybudianto** [comment]
Try importing BrowserModule to AppModule
```
import { BrowserModule } from '@angular/platform-browser'

@NgModule({
    declaractions: ...,
    imports: [ 
        BrowserModule 
   ]
})
export class AppModule {}
```

**Comment by oluijks** [comment]
Perfect, thank you!
