### ISSUE TITLE
npm start does not work

### ISSUE THREAD

**Issue by crain** [antonybudianto/angular2-starter#139]
## Issue Overview
Node is complaining that it can't find the module gulp-util. After I added the missing module to the dev dependencies it worked.

## Issue Description

> module.js:327
>     throw err;
>     ^
> 
> Error: Cannot find module 'gulp-util'
>     at Function.Module._resolveFilename (module.js:325:15)
>     at Function.Module._load (module.js:276:25)
>     at Module.require (module.js:353:17)
>     at require (internal/module.js:12:17)
>     at Object.<anonymous> (C:\dev\hathor_new\config\gulp\tasks\build.js:2:12)
>     at Module._compile (module.js:409:26)
>     at Object.Module._extensions..js (module.js:416:10)
>     at Module.load (module.js:343:32)
>     at Function.Module._load (module.js:300:12)
>     at Module.require (module.js:353:17)
> 

## Reproducables
Clone the repository
Run "npm install"
Run "npm start"

## Information
|                      	|                                 	|
|---------------------	|---------------------------------	|
| **Operating System** 	| Windows 	|
| **Node version**     	| 4.x   	|
| **NPM Version**      	| 2.x    	|
| **Environment**       | Browser          |

**Comment by antonybudianto** [comment]
Sorry we (and Angular itself) don't support npm 2

**Comment by kennyhyun** [comment]
didn't know because I had installed gulp globally.
Good to know I was using npm 2. I'm happy with npm 3 now :)
https://github.com/felixrieseberg/npm-windows-upgrade
