### ISSUE TITLE
IE11 support ?

### ISSUE THREAD

**Issue by dharders** [antonybudianto/angular2-starter#14]
This might be more of an angular 2 issue, but here goes:

I've been successfully using your (awesome) angular2-starter with Chrome, Firefox on Win 7. I tested it on IE11 recently, both gulp serve-dev & serve-build fail to bootstrap the app. (stuck at spinner).

Dev tools reported: "Object doesn't support property or method 'keys'", which I figured I needed an es6-shim for. *Note: the official angular.io 5 MIN QUICKSTART live example plunkr has the same error with IE11* (https://angular.io/resources/live-examples/quickstart/ts/plnkr.html)

I solved the official angular error through loading the es6-shim via script src="https://cdnjs.cloudflare.com/ajax/libs/es6-shim/0.34.1/es6-shim.min.js"

However, doing the same to your index.html file does not work. It removes the exception reported in ie11 dev tools, but is still stuck at the spinner (with no errors in console).

How do I get this to work with your build setup ? Is it a SystemJS issue ?

Thanks for such a great tool !!

**Comment by antonybudianto** [comment]
https://angular.io/docs/ts/latest/quickstart.html#!#es6support

The official guide said you must put the script tag above the others, but if it didn't solve, maybe it's either beta or SystemJS issue. Thank you for letting me know.

**Comment by dharders** [comment]
Follow up... seems to be an Angular 2 Beta 1 issue:

Potentially unhandled rejection [4] SyntaxError: The use of a keyword for an identifier is invalid
   at evalExpression (http://127.0.0.1:3000/node_modules/angular2/bundles/angular2.dev.js:452:5)
   at TemplateCompiler.prototype._createViewFactoryRuntime .....

Angular 2 Beta 0 works with es6-shim in IE11.

Modifying your package.json dependencies from: "angular2": "2.0.0-beta.1"  to "angular2": "2.0.0-beta.0" and running an npm install then gulp fixed the issue in IE11 (with the es6-shim).

**Comment by antonybudianto** [comment]
@dharders : Oh I see, I also filed an issue there because of mangling issue since updating to **beta.1**, and many others issue related to **beta.1** too. Let's wait for them to fix.
Anyway thank you for the confirmation and enjoy coding :+1:
