### ISSUE TITLE
Uncaught TypeError: Module @angular/core not declared as a dependency.

### ISSUE THREAD

**Issue by PRR24** [antonybudianto/angular2-starter#141]
* fresh copy from zip (head)
* npm install
* npm run serve-build
Result: app-cf3361f664.js:1 Uncaught TypeError: Module @angular/core not declared as a dependency.

Ubuntu 16.04
npm 3.9.5
node 6.2.2
Chrome 51.0.2704.106 (Official Build) (64-bit)
Same prob when using Firefox.

Just serving dev version works perfectly.
Any suggestions?

I would guess it is connected to some recent change in external tooling issue, as otherwise why no one found it before + 
- have similar error with rc4 version of starter.
- tried to use systemjs-builder directly skipping your tooling and resulted similar error.

In my machine:
$ npm list --depth=0
angular2-starter@1.0.0-rc.5 /home/rene/IdeaProjects/temp/angular2-starter-master
├── @angular/common@2.0.0-rc.5
├── @angular/compiler@2.0.0-rc.5
├── @angular/core@2.0.0-rc.5
├── @angular/forms@0.3.0
├── @angular/http@2.0.0-rc.5
├── @angular/platform-browser@2.0.0-rc.5
├── @angular/platform-browser-dynamic@2.0.0-rc.5
├── @angular/router@3.0.0-rc.1
├── @ngstarter/systemjs-extension@1.0.0-rc.4
├── bootstrap-sass@3.3.7
├── browser-sync@2.14.0
├── codelyzer@0.0.26
├── connect-history-api-fallback@1.3.0
├── core-js@2.4.1
├── del@2.2.2
├── font-awesome@4.6.3
├── glob@7.0.5
├── gulp@3.9.1
├── gulp-cssnano@2.1.2
├── gulp-if@2.0.1
├── gulp-protractor@3.0.0
├── gulp-rev@7.1.2
├── gulp-rev-replace@0.4.3
├── gulp-sass@2.3.2
├── gulp-sourcemaps@1.6.0
├── gulp-template@4.0.0
├── gulp-tslint@6.0.2
├── gulp-typescript@2.13.6
├── gulp-uglify@2.0.0
├── gulp-useref@3.1.0
├── jasmine-core@2.4.1
├── jquery@3.1.0
├── karma@1.1.2
├── karma-coverage@1.1.1
├── karma-ie-launcher@1.0.0
├── karma-jasmine@1.0.2
├── karma-phantomjs-launcher@1.0.1
├── karma-sourcemap-loader@0.3.7
├── lodash@4.15.0
├── phantomjs-prebuilt@2.1.12
├── remap-istanbul@0.6.4
├── require-dir@0.3.0
├── run-sequence@1.2.2
├── rxjs@5.0.0-beta.6
├── systemjs@0.19.37
├── tslint@3.14.0
├── typings@1.3.2
├── yargs@4.8.1
└── zone.js@0.6.15

**Comment by PRR24** [comment]
More info: Forcing systemjs-builder@0.15.25 solves the problem

**Comment by antonybudianto7** [comment]
Thanks for the report! I'd take a look when free time

**Comment by antonybudianto7** [comment]
looks like SystemJS had a bad commit these days, my webpack's build worked with ngc while systemjs builder not. 
Need more investigation

**Comment by antonybudianto** [comment]
They've fixed it in https://github.com/systemjs/builder/commit/7197bfa81d5e5c96a9b906590f9d9d00d82735ee
