### ISSUE TITLE
Getting error when starting the project

### ISSUE THREAD

**Issue by anupamarachuri** [antonybudianto/angular2-starter#142]
<GitHub issues are ONLY for BUG reports and FEATURE requests>
<Questions or support can be send to StackOverflow>
<PLEASE DO FOLLOW and fill the issue template below. Don't skip or remove any section>

## Issue Overview
Downloaded the code. npm install done. have correct version of node and npm.

## Issue Description
Getting below error on npm install:
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN prefer global node-gyp@3.4.0 should be installed with -g

> node-sass@3.8.0 install C:\angular2-starter-master\angular2-starter-master\node_modules\node-sass
> node scripts/install.js

Binary downloaded and installed at C:\angular2-starter-master\angular2-starter-master\node_modules\node-sass\vendor\win32-x64-47\binding.node

> phantomjs-prebuilt@2.1.12 install C:\angular2-starter-master\angular2-starter-master\node_modules\phantomjs-prebuilt
> node install.js

PhantomJS not found on PATH
Download already available at C:\a584775\AppData\Local\Temp\phantomjs\phantomjs-2.1.1-windows.zip
Verified checksum of previously downloaded file
Extracting zip contents
Removing C:\angular2-starter-master\angular2-starter-master\node_modules\phantomjs-prebuilt\lib\phantom
Copying extracted folder C:\a584775\AppData\Local\Temp\phantomjs\phantomjs-2.1.1-windows.zip-extract-1472153469770\phantomjs-2.1.1-windows -> C:\angular2-starter-master\angular2-starter-master\node_modules\phantomjs-prebuilt\lib\phantom
Writing location.js file
Done. Phantomjs binary available at C:\angular2-starter-master\angular2-starter-master\node_modules\phantomjs-prebuilt\lib\phantom\bin\phantomjs.exe

> node-sass@3.8.0 postinstall C:\angular2-starter-master\angular2-starter-master\node_modules\node-sass
> node scripts/build.js

"C:\angular2-starter-master\angular2-starter-master\node_modules\node-sass\vendor\win32-x64-47\binding.node" exists.
 testing binary.
Binary is fine; exiting.

> angular2-starter@1.0.0-rc.5 postinstall C:\angular2-starter-master\angular2-starter-master
> typings install

typings ERR! message Unable to connect to "https://api.typings.org/entries/npm/lodash/tags/4.0.0%2B20160723033700"
typings ERR! caused by connect ETIMEDOUT 104.24.112.177:443

typings ERR! cwd C:\angular2-starter-master\angular2-starter-master
typings ERR! system Windows_NT 6.1.7601
typings ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\angular2-starter-master\\angular2-starter-master\\node_modules\\typings\\dist\\bin.js" "install"
typings ERR! node -v v5.7.1
typings ERR! typings -v 1.3.2
typings ERR! code EUNAVAILABLE

typings ERR! If you need help, you may report this error at:
typings ERR!   <https://github.com/typings/typings/issues>

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN optional Skipping failed optional dependency /browser-sync/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v5.7.1
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE
npm ERR! angular2-starter@1.0.0-rc.5 postinstall: `typings install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-starter@1.0.0-rc.5 postinstall script 'typings install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     typings install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-starter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-starter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\angular2-starter-master\angular2-starter-master\npm-debug.log

Getting the below error on running npm start:
 Failed at the angular2-starter@1.0.0-rc.5 start script 'gulp serve-dev'.

## Reproducables
<Please explain the way to reproduce your issue, or even better with Plunker link>

## Information
|                      	|                                 	|
|---------------------	|---------------------------------	|
| **Operating System** 	| Windows 7	|
| **Node version**     	| 5.7.1|
| **NPM Version**      	| 3.6.0	|
| **Environment**       | Did not make any change to code. Not sure.       |

**Comment by antonybudianto7** [comment]
Sorry can't get to reproduce, can you try to re `npm install`

**Comment by anupamarachuri** [comment]
Hi @antonybudianto7 .. It worked. There was proxy setting issue. I had explicitly give the proxy settings in a new .typingssrc file.

I have a request for you. We are trying to make use of angular2-schema-form. Can you please provide steps to integrate with it in this solution.

**Comment by antonybudianto** [comment]
For integration things, you should follow the plugin/lib guides, mostly you'll need to configure this [file](https://github.com/antonybudianto/angular2-starter/blob/master/src/systemjs.conf.js)
