### ISSUE TITLE
RC6 AOT compilation

### ISSUE THREAD

**Issue by mevinDhun** [antonybudianto/angular2-starter#150]
Hi, 

First of all, i would like to say its an awesome starter project, i tried many seed projects but found this one really good. (Y)  I am currently using it for developing a new website in JIT compilation. I am now trying to use the Ahead of time (AOT) compiler with it but i am a bit lost. Is it possible to integrate AOT compilation in this sample? Can you provide me with some steps or guide me how to implement it as a feature? 

Thanks

**Comment by antonybudianto** [comment]
Currently there's compilation issue in RC6, you can take a look at `feat-compiler-cli` branch

**Comment by antonybudianto** [comment]
The error resolved, will be available in new Starter 2.0 project since I'll switch to Webpack (breaking change)

**Comment by antonybudianto7** [comment]
https://github.com/antonybudianto/angular-webpack-starter
