### ISSUE TITLE
--env issue 

### ISSUE THREAD

**Issue by Jarkan** [antonybudianto/angular2-starter#152]
Hello,
I think that the setting of the global.ENV is never performed. When you type into terminal "gulp default --env=testing" and change in gulp task to perform development mode when env is set on "testing" you will see that "global.ENV" in systemjs.conf.js is "undefined" and for all cases it will be set to "development".

And now my question is: what i can change/do to have this variable updated?

**Edit: ok, i found answer here** https://github.com/antonybudianto/angular2-starter/issues/100

**Comment by antonybudianto** [comment]
+1 for looking old issues first 👍
