### ISSUE TITLE
support for Component-Relative URLs to component templates and style files

### ISSUE THREAD

**Issue by tolyanich** [antonybudianto/angular2-starter#156]
Hi.
Angularjs support relative path for component templates and style file. It is very useful for when projects start growing and you begin to move components inside project structure.
Currently if you try to use it with this starter it will not work. First things is in dev mode js files served from src/app/tmp/<component> path and html files served directly from src/app/<component>. May be is a good idea to add watcher for html and copy them to src/tmp folder as well.  And probably some enhancement for prod build will be required.
Thanks

**Comment by antonybudianto** [comment]
It's on the work, but it will change the whole workflow, I'm switching to webpack.

**Comment by antonybudianto7** [comment]
https://github.com/antonybudianto/angular-webpack-starter
