### ISSUE TITLE
Reduce the size of the build

### ISSUE THREAD

**Issue by jonben** [antonybudianto/angular2-starter#159]
The way you create a minified build is great but the assets are still more than 1 MB total for a project that's nearly empty, my project based on one of your previous starter kits is nearly 2 MB only for the 2 JS and CSS files as assets.

Do you have any idea what could be done to reduce the size of Angular 2 files?

**Comment by antonybudianto7** [comment]
You may want to look at new https://github.com/antonybudianto/angular-webpack-starter,
the bundle is fully-optimized there. For this starter, it's hard to do it without Webpack
