### ISSUE TITLE
karma.conf.js issues

### ISSUE THREAD

**Issue by talmog** [antonybudianto/angular2-starter#16]
Hi,
Thanks again for the starter, I have few more questions please.

1) in Karma.conf.js under "files" should the node_modules files be watched? are they expected to change?
2) I am trying to the auto watch for Karma so it runs the tests after every save. I was able to achieve that easily, but he typescript is not being re-converted. I have tried using different preprocessors, but they also run only once.

Thank you so much!

**Comment by antonybudianto** [comment]
Hi,
1) I also think it should not be watched, but I wait until next ng2 release since they have some changes for testing
2) Not sure about this, you might need `restartOnFileChange` option to restart Karma and it'll rerun the remap

**Comment by talmog** [comment]
Thank you
