### ISSUE TITLE
" should be ' when adding new route

### ISSUE THREAD

**Issue by svennela** [antonybudianto/angular2-starter#165]
## Issue Overview
Adding new route
## Issue Description
" should be '

## Reproducables
add below router
import { Routes } from '@angular/router';

import { MyLink1Component } from './mylink1.component';

export const MyLink1Routes: Routes = [
  { path: 'mylink1', component: MyLink1Component }
];

### Error

(quotemark) app/mylink1/mylink1.module.ts[3, 34]: " should be '

stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^
Error: Failed to lint: app/mylink1/mylink1.module.ts [3, 34]: " should be '.

npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.6.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE
npm ERR! angular2-starter@1.0.0 start: `gulp serve-dev`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular2-starter@1.0.0 start script 'gulp serve-dev'.
npm ERR! This is most likely a problem with the angular2-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp serve-dev
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-starter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls angular2-starter
npm ERR! There is likely additional logging output above.

**Comment by antonybudianto7** [comment]
looks like you used `"` double quotes where tslint wanted `'` single quote

**Comment by svennela** [comment]
I don't see " in my route file

**Comment by antonybudianto7** [comment]
the warning is in your module file
```
(quotemark) app/mylink1/mylink1.module.ts[3, 34]: " should be '
```

**Comment by svennela** [comment]
Thanks.
