### ISSUE TITLE
Attribute selectors

### ISSUE THREAD

**Issue by ailegion** [antonybudianto/angular2-starter#166]
<GitHub issues are ONLY for BUG reports and FEATURE requests>
<Questions or support can be send to StackOverflow>
<PLEASE DO FOLLOW and fill the issue template below. Don't skip or remove any section>

## Issue Overview
Cannot implement attribute selector

## Issue Description
Due to restrictions in naming of component selector, attribute selectors cannot be implemented 

## Reproducables
Try to define a component as attribute selector for table row ex: 'tr[as-your-component]' - you will hit the selector naming error.
Ex: http://stackoverflow.com/questions/34556277/angular2-table-rows-as-component

## Information
|                      	|                                 	|
|---------------------	|---------------------------------	|
| **Operating System** 	| Windows 10 	|
| **Node version**     	| 5.10.0  |
| **NPM Version**      	| 3.10.8   |
| **Environment**       | Browser  |

**Comment by antonybudianto** [comment]
you should use @Directive instead of @Component then

**Comment by antonybudianto** [comment]
https://angular.io/docs/ts/latest/guide/attribute-directives.html
