### ISSUE TITLE
CSS bootstrap-material-design.css is not included in the bundle.XXX.css 

### ISSUE THREAD

**Issue by nivikamal** [antonybudianto/angular2-starter#167]
<GitHub issues are ONLY for BUG reports and FEATURE requests>
<Questions or support can be send to StackOverflow>
<PLEASE DO FOLLOW and fill the issue template below. Don't skip or remove any section>

## Issue Overview
I try to add node_modules\bootstrap-material-design\dist\css\bootstrap-material-design.css in the index.html and  npm run build. and I don;t see bootstarp material css injected into bundle

## Issue Description
I try to add node_modules\bootstrap-material-design\dist\css\bootstrap-material-design.css in the index.html and  npm run build. and I don;t see bootstarp material css injected into bundle

## Reproducables
<Please explain the way to reproduce your issue, or even better with Plunker link>

## Information
|                      	|                                 	|
|---------------------	|---------------------------------	|
| **Operating System** 	| Windows/OSX/Ubuntu/orYourOSHere 	|
| **Node version**     	| 4.x/5.x/orYourNodeVersionHere   	|
| **NPM Version**      	| 2.x/3.x/orYourNPMVersionHere    	|
| **Environment**       | Browser/Mobile/WebWorker          |

**Comment by antonybudianto** [comment]
Did you put it inside https://github.com/antonybudianto/angular2-starter/blob/master/src/index.html#L8 ?

**Comment by antonybudianto** [comment]
Please give reproducable too
