### ISSUE TITLE
Throw error when referencing latest ng2-bootstrap

### ISSUE THREAD

**Issue by tsampath** [antonybudianto/angular2-starter#169]
<GitHub issues are ONLY for BUG reports and FEATURE requests>
<Questions or support can be send to StackOverflow>
<PLEASE DO FOLLOW and fill the issue template below. Don't skip or remove any section>

## Issue Overview
Throw error when referencing latest ng2-bootstrap

## Issue Description
When imported 3rd party component that has reference to latest ng2-bootstrap, it throws below error 
/node_modules/ng2-bootstrap/components/buttons/button-checkbox.directive.d.ts(14,22): error TS1005: '=' expected.
button-checkbox.directive.d.ts has below line at 14 
private readonly trueValue;

This  indicates that starter should use TypeScript 2.0 to build package. How can we upgrade this starter to use TypeScript 2.0? Tried that already. But gave some other issues.   

## Reproducables
npm i ng2-dropdown-multiselect
use it inside package 

## Information
|                      	|                                 	|
|---------------------	|---------------------------------	|
| **Operating System** 	| Windows	|
| **Node version**     	| 5.2   	|
| **NPM Version**      	|3.3.12    	|
| **Environment**       | Browse      |

**Comment by antonybudianto** [comment]
Sorry I don't accept any 3rd party integration issues here, also the latest starter is already using TypeScript 2.0.3
