### ISSUE TITLE
PhantomJS support

### ISSUE THREAD

**Issue by talmog** [antonybudianto/angular2-starter#17]
Hi again,

I am trying to use phantomJS as a browser option.
I have installed karma-phantomjs-launcher and added phantomJS to the list of browsers.
I am getting this error:
```
 Error: 'undefined' is not a constructor (evaluating 'new exports.Map()')
  	Error loading http://localhost:9876/angular2/src/platform/browser/browser_adapter
      at //node_modules/systemjs/dist/system.src.js:741
      at M (/node_modules/systemjs/dist/system-polyfills.js:4)
      at H (/node_modules/systemjs/dist/system-polyfills.js:4)
      at /node_modules/systemjs/dist/system-polyfills.js:4
      at /node_modules/systemjs/dist/system-polyfills.js:4
      at /node_modules/systemjs/dist/system-polyfills.js:4
      at /node_modules/systemjs/dist/system-polyfills.js:4
      at /node_modules/angular2/bundles/angular2-polyfills.js:493
      at /node_modules/angular2/bundles/angular2-polyfills.js:118
      at run (/node_modules/angular2/bundles/angular2-polyfills.js:138)
      at zoneBoundFn (/node_modules/angular2/bundles/angular2-polyfills.js:111)

```

any idea what is going on?
Thank you

**Comment by antonybudianto** [comment]
I also tried using PhantomJS2 and still no luck, even after using `es6-shim`, I'll try it in next ng2 release

**Comment by zachallen** [comment]
I've gotten PhantomJS2 to work with your starter by putting `traceur-rungime` and `system-polyfills` in karma.conf.js's files section:
>    files: [
>      'node_modules/traceur/bin/traceur-runtime.js', // Required by PhantomJS2, otherwise it shouts ReferenceError: Can't find variable: require

>      {pattern: 'node_modules/angular2/bundles/angular2-polyfills.js', included: true, watched: true},
>      {pattern: 'node_modules/systemjs/dist/system.src.js', included: true, watched: true},
>      {pattern: 'node_modules/rxjs/bundles/Rx.js', included: true, watched: true},
>      {pattern: 'node_modules/angular2/bundles/angular2.dev.js', included: true, watched: true},
>      {pattern: 'node_modules/angular2/bundles/router.dev.js', included: true, watched: true},
>      {pattern: 'node_modules/angular2/bundles/testing.dev.js', included: true, watched: true},
>      {pattern: 'test/test-helpers/**/*.js', included: true, watched: true},
>      {pattern: 'karma-test-shim.js', included: true, watched: true},

>      { pattern: 'node_modules/systemjs/dist/system-polyfills.js', included: false, watched: false }, // PhantomJS2 (and possibly others) might require it


>      // paths loaded via module imports

**Comment by talmog** [comment]
thank you @zachallen !!!

**Comment by antonybudianto** [comment]
that's great @zachallen , will add to master soon
