### ISSUE TITLE
the gulp-cssnano changes the z-index of the minified css files

### ISSUE THREAD

**Issue by ovione** [antonybudianto/angular2-starter#172]
Issue Overview
---------------------------
the gulp-cssnano changes the z-index of the minified css files
Issue Description
---------------------------
this happens when we issue a 'gulp build'

my solution
---------------------------
The solution I found is in the build.js in the task 'build-assets' to add to the 'gulp-cssnano' plugin the following:
cssnano({zindex: false})
that means that the minification will not touch the z-indexes.

**Comment by antonybudianto7** [comment]
I accept the solution. Can you open a pull request for this?
Thank you.

**Comment by ovione** [comment]
yes I will be glad to do but I'm trying to figure out how to do a PR :)
when I do a 'new pull request' I have a 'Compare changes' screen with the 'create pull request' button disabled.

I have never contributed thats why I'm trying to figure out how to do it.

**Comment by antonybudianto7** [comment]
you can edit the file directly and submit the PR there

**Comment by ovione** [comment]
I found how.
I forked the project to my github, then I pushed it and I sedt a pull request.
I hope thats correct
cheers
O
