### ISSUE TITLE
test pass with Chrome but not with Phantomjs

### ISSUE THREAD

**Issue by ovione** [antonybudianto/angular2-starter#174]
## Issue Overview
test pass with Chrome but not with Phantomjs

## Issue Description
test pass with Chrome but some of them does not pass with Phantomjs
I tried to include phantomjs-polyfill but that doesn't do the trick.
My app is quite big and at some point I switched to Chrome but now when I want to use it with jenkings I need phantomjs and some tests don't pass anymore.
Any help would be welcome.

thanks

## Information
The version of the 'angular2-starter' I use is '1.0.0-rc.7'.

**Comment by antonybudianto7** [comment]
Can you try on latest snapshot of the starter?

**Comment by ovione** [comment]
yes I could try the latest starter. That would be better.
The errors are two.
One is that the ngOnInit of a component was not called when navigated to it and the other is that a method was not called in our component when a button was clicked.
Maybe phantomjs needs some type of pollyfill but I dont know.

Because the project is quite large we should decide now if we continue with systemjs.

The angular2 guys are building a tool called angular-cli still in beta and that they dropped Systemjs in favor of webpack. So maybe we should go towards a solution that uses webpack.

But I don't know if I should use angular-cli or your angular-webpack-starter.
I'm reading now about webpack to be more informed.
If you have any suggestions they are more than welcome.

thanks









But anywyas I dont know

**Comment by antonybudianto7** [comment]
Yeah, from what I experienced, SystemJS is a bit of pain: Adding new package even needs to be configured, not stable enough, still slow even it's a loader not bundler.
After moving to Webpack, life is easier, haha, many amazing features can be added like AoT, Lazy load, tree-shaking out-of-the-box and more. 
I recommend you to learn it :+1: 

FYI I may not maintain this repo anymore and recommend [angular-webpack-starter](https://github.com/antonybudianto/angular-webpack-starter)

**Comment by ovione** [comment]
thanks for your advice Antony.

I will switch to your angular-webpack-starter.
But first I have to read about webpack  and I let you know when my migration happens with your latest version if any errors appear.

By the do you recommend angular-webpack-starter or angular-cli.
Are both doing the same or are they complementary ?

cheers
O

**Comment by antonybudianto7** [comment]
Actually I tried angular-cli first, but feel stuck at some point where I needed some features that's not available, and the webpack config is blackboxed and currently there's no way to override them/customize it.

If you just need normal dev workflow (serve dev, unit testing + coverage, e2e testing, prod build), you can go with angular-cli, with note:
- when new angular version is out, you cannot upgrade them directly (can be peerDependencies issue or incompabilities), it's best to wait their update
- you're okay without webpack customization

You can join https://gitter.im/angular/angular-cli to see how the users use it and their problems too.

I'd try to make my webpack-starter more easy to migrate each other.
