### ISSUE TITLE
problem between npm start and npm run build on style sheet

### ISSUE THREAD

**Issue by foxjazz** [antonybudianto/angular2-starter#176]
<GitHub issues are ONLY for BUG reports and FEATURE requests>
<Questions or support can be send to StackOverflow>
<PLEASE DO FOLLOW and fill the issue template below. Don't skip or remove any section>

## Issue Overview
The home display is different based on the css info after deploying a build.

## Reproducables
my version of the starter plus my code.
run npm start and check home page. The color is purple and green.
run npm run build and deploy, the color is NOT purple and green
https://github.com/foxjazz/eveview.git

## Information
using windows
|                      	|                                 	|
|---------------------	|---------------------------------	|
| **Operating System** 	| Windows/OSX/Ubuntu/orYourOSHere 	|
| **Node version**     	| 4.x/5.x/orYourNodeVersionHere   	|
| **NPM Version**      	| 2.x/3.x/orYourNPMVersionHere    	|
| **Environment**       | Browser/Mobile/WebWorker          |

**Comment by antonybudianto** [comment]
sorry, it's not reproducable on my machine, both have same color

what node and npm version you use?

**Comment by antonybudianto** [comment]
Closing as no response in a week, feel free to notify me for re-open
