### ISSUE TITLE
remove Todolist module

### ISSUE THREAD

**Issue by jose4125** [antonybudianto/angular2-starter#180]
<GitHub issues are ONLY for BUG reports and FEATURE requests>
<Questions or support can be send to StackOverflow>
<PLEASE DO FOLLOW and fill the issue template below. Don't skip or remove any section>

## Issue Overview
remove the TodolistModule and then the project doesn't load and showed an error 

## Issue Description
I was trying to remove the TodolistModule and then the project doesn't load and showed an error No provider for ApplicationRef! 

## Reproducables
remove the TodolistModule from the app.module and remove the import { TodolistModule }

## Information
|                      	|                                 	|
|---------------------	|---------------------------------	|
| **Operating System** 	| Windows/OSX/Ubuntu/orYourOSHere 	|
| **Node version**     	| 4.x/5.x/orYourNodeVersionHere   	|
| **NPM Version**      	| 2.x/3.x/orYourNPMVersionHere    	|
| **Environment**       | Browser/Mobile/WebWorker          |

**Comment by antonybudianto7** [comment]
I'll investigate on weekend, thanks for the report

**Comment by antonybudianto** [comment]
Turned out I forgot to import required `BrowserModule`
