### ISSUE TITLE
import { filter } from 'lodash';

### ISSUE THREAD

**Issue by ShridharGowda** [antonybudianto/angular2-starter#182]
<GitHub issues are ONLY for BUG reports and FEATURE requests>
<Questions or support can be send to StackOverflow>
<PLEASE DO FOLLOW and fill the issue template below. Don't skip or remove any section>

## Issue Overview
import { filter } from 'lodash';
this line showing build error at @todolist/completed-filter.pipe.ts

## Issue Description
<Please explain the issue in details>

## Reproducables
<Please explain the way to reproduce your issue, or even better with Plunker link>

## Information
Use import { filter } from '@types/lodash';

**Comment by antonybudianto** [comment]
Please complete the issue template, cannot reproduce the issue

**Comment by antonybudianto7** [comment]
Btw you cannot do
```
import { filter } from '@types/lodash';
```

you're supposed to do it with
```
import { filter } from 'lodash';
```
