### ISSUE TITLE
npm run build is broken

### ISSUE THREAD

**Issue by foxjazz** [antonybudianto/angular2-starter#185]
## Issue Overview
when I clone the starter and I run the command npm run build usually it creates a build directory with one index.html file and a couple of folders.

## Issue Description
npm run build doesn't work as expected.

what is expected is a single index.html file, what is added is multiple .html files.

## Reproducables
git clone thestarter 
npm install
npm run build

OS: mac or git bash on windows.

no changes were made, latest version of node.

## Information
|                      	|                                 	|
|---------------------	|---------------------------------	|
| **Operating System** 	| windows/mac 	|
| **Node version**     	| 5 	|
| **NPM Version**      	| 3   	|
| **Environment**       | Browser/Mobile/WebWorker          |

**Comment by antonybudianto** [comment]
I see, it's expected because now we use relative path, and I don't use AoT here so the component's html and css will be on the root
