### ISSUE TITLE
No file change on the screen, despite recompile (RaydonZhu comment)

### ISSUE THREAD

**Issue by Michael-xxxx** [antonybudianto/angular2-starter#187]
Hi
I face the same issue: 
RaydonZhu commented on 23 Nov 2016 • edited

I am trying to use this. everything works fine. However, it won't be able to 'recompile' automatically if file changes. For example, I change the text in a html file, and it seems that the app catched the changes and recompiled. However, i didn't see any changes on the screen. I had to rebuild it again, and then i could see the changes on the screen.
Why?
Thanks!

Thanks a lot in advance

**Comment by antonybudianto** [comment]
Please give a repro, I cannot repro using latest master

**Comment by Michael-xxxx** [comment]
Hi Antony,
I investigated the issue. If I change index.html (e.g. the title) everything is fine the change goes to the browser. But if I change navbar.html e.g.
 <li><a [routerLink]="['/']">HomeXX</a></li>
the change is not visible at the browser.
On the commandline I see
[BS] File changed: src\app\shared\navbar\navbar.html
but in the tmp folder the file navbar.html is unchanged

**Comment by antonybudianto** [comment]
Sorry but cannot reproduce, it works on my machine, are you sure you're editing the right file? (Perhaps you're editing the tmp file or build file)

**Comment by Michael-xxxx** [comment]
No I don't change the file in tmp or build folder
[BS] File changed: src\app\shared\navbar\navbar.html
but if you can't reproduce it the issue should be closed

**Comment by antonybudianto** [comment]
Hmm, what OS do you use? maybe OS specific

**Comment by Michael-xxxx** [comment]
Yes, you are right. It is a platfrom problem. I'm using Windows 10 and
component.js 
function convertToTmpPath(file) {
    return file.path.replace(/src\/app\//, config.tmpApp);
}
goes only for linux
I hope this will work with linux and windwos:
function convertToTmpPath(file) {
    var re = new RegExp('src\\' + path.sep + 'app\\' + path.sep,"g");
    return file.path.replace(re, config.tmpApp);
}

**Comment by antonybudianto** [comment]
@Michael-xxxx , can you create the PR? Thank you!
