### ISSUE TITLE
Serving from the root folder

### ISSUE THREAD

**Issue by aswath-veersoft** [antonybudianto/angular2-starter#190]
<GitHub issues are ONLY for BUG reports and FEATURE requests>
<Questions or support can be send to StackOverflow>
<PLEASE DO FOLLOW and fill the issue template below. Don't skip or remove any section>

## Issue Overview
I want to serve from the root folder, not from ./src/
I did some changes, and the gulp serve-dev is fine.
However, if do 'gulp build', it does not build.

What changes should be made so that it serves from the root folder.?

**Comment by antonybudianto7** [comment]
I think it's more complicated to serve from there, many things need to be set and it's out of this starter scope.

**Comment by aswath-veersoft** [comment]
Thanks.
I have an existing app.  I want the new angular2 module to be served from subfolder.
ex.  I already have an application serving at localhost:8000, and I am enhancing the application using angular2.  So, I want to be served from http://localhost:8000/src/index.html

Any pointer on this.

**Comment by antonybudianto7** [comment]
My starter isn't designed for serving for multi-apps/subfolder, but you can still host the build result under any routes you want, just play with web server setting.

**Comment by aswath-veersoft** [comment]
Yes, the final build can be hosted in the subfolder.  However, then, I am stuck for iterative development.  

Any pointers on what other seed projects can be used for subfolders for both dev and prod?  Thanks.

**Comment by antonybudianto** [comment]
https://github.com/mgechev/angular-seed
