### ISSUE TITLE
lodash Partial - too old Typescript used

### ISSUE THREAD

**Issue by Koshmaar** [antonybudianto/angular2-starter#195]
## Issue Description

I copied the latest release, and got the error as below.

This is a fresh thing:  https://github.com/DefinitelyTyped/DefinitelyTyped/issues/14311

Simply setting typescipt to be 2.1.0 in package.json (as it was 2.0.6) made the error go away, and now app is compiling.

Perhaps you should update the starter :)

## Reproducables

$ npm install
$ npm install gulp-cli -g
$ npm install gulp -D
$ npm start

> angular2-starter@1.0.1 start E:\WWW\WebdevHomepage\admin
> gulp serve-dev

============ Angular 2 Starter ============
Current environment: development
- Change environment via --env or NODE_ENV
- env.json is not detected. You can create one on project root
===========================================
[16:21:44] Using gulpfile E:\WWW\WebdevHomepage\admin\gulpfile.js
[16:21:44] Starting 'sass'...
[16:21:44] Starting 'clean-ts-app'...
[16:21:44] Starting 'env'...
[16:21:44] Starting 'watch-ts'...
[16:21:45] Finished 'watch-ts' after 24 ms
[16:21:45] Starting 'watch-sass'...
[16:21:45] Finished 'watch-sass' after 3.95 ms
[16:21:45] src/app/shared/constant/env.ts is generated successfully
[16:21:45] Finished 'env' after 49 ms
[16:21:45] Finished 'clean-ts-app' after 52 ms
[16:21:45] Starting 'tsc-app'...
**[16:21:45] Compiling E:\WWW\WebdevHomepage\admin\src\app\shared\constant\env.ts...
E:/WWW/WebdevHomepage/admin/node_modules/@types/lodash/index.d.ts(245,25): error TS2304: Cannot find name 'Partial'.**
[16:21:46] TypeScript: 1 semantic error
[16:21:46] TypeScript: emit succeeded (with errors)
[16:21:46] Finished 'sass' after 1.74 s
E:/WWW/WebdevHomepage/admin/node_modules/@types/lodash/index.d.ts(245,25): error TS2304: Cannot find name 'Partial'.

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "E:\\Tools\\nodejs\\node.exe" "E:\\Tools\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! angular2-starter@1.0.1 start: `gulp serve-dev`
npm ERR! Exit status 1

## Information
|                      	|                                 	|
|---------------------	|---------------------------------	|
| **Operating System** 	| Windows 7 x64 	|
| **Node version**     	| 6.9.1   	|
| **NPM Version**      	| 3.10.8    	|
| **Environment**       | Cygwin console       |

**Comment by antonybudianto** [comment]
https://github.com/antonybudianto/angular2-starter/blob/master/package.json#L93
