### ISSUE TITLE
does it support lazy loading?

### ISSUE THREAD

**Issue by oztek22** [antonybudianto/angular2-starter#197]
<GitHub issues are ONLY for BUG reports and FEATURE requests>
<Questions or support can be send to StackOverflow>
<PLEASE DO FOLLOW and fill the issue template below. Don't skip or remove any section>

## Issue Overview
I'm looking for gulp starter pack to work with browserify which supports lazyloading.

## Issue Description
While searching my issue in already asked issues I read that you commented to use your webpack starter pack. My question is rather gulp support lazyload or not and If not than Why does gulp not support lazy load?

**Comment by antonybudianto** [comment]
@oztek22  It's hard to make it work with current workflow, I'm open for PR though.
