### ISSUE TITLE
Upgrade to Angular 5 causing remap-istanbul html report generation to fail

### ISSUE THREAD

**Issue by pgarge** [antonybudianto/angular2-starter#210]
<GitHub issues are ONLY for BUG reports and FEATURE requests>
<Questions or support can be send to StackOverflow>
<PLEASE DO FOLLOW and fill the issue template below. Don't skip or remove any section>

## Issue Overview
Upgrade to Angular 5 causing remap-istanbul html report generation to fail

## Issue Description
I have been using your example so far with Angular 4 and SystemJS. When I upgrade to Angular 5 and keep all the packages the same I run into an issue described here:

https://github.com/SitePen/remap-istanbul/issues/45

I just wanted to find out if you have seen this issue and if there is a workaround. Thanks!!

**Comment by antonybudianto** [comment]
sorry it's been long since I maintained this project, you can post to https://stackoverflow.com for more help
