### ISSUE TITLE
compile ts files to tmp folder

### ISSUE THREAD

**Issue by UnnoTed** [antonybudianto/angular2-starter#22]
it's really bad to find a file and it feels disorganized

**Comment by antonybudianto** [comment]
if i compile it on one tmp folder, then i also need to copy the asset references (template html, css...) to the same path and need to adjust the index.html

i think you may want to set the transpiler to typescript in `index.html` and turn off `tsc-app` and `watch-ts` in `serve-dev` task so it can load ts directly (only for development of course)

or you can use `gulp clean` to wipe all compiled files (ts or sass)

**Comment by UnnoTed** [comment]
since it uses SystemJS you could load ts files from it with the `transpiler` config
https://github.com/systemjs/systemjs#browser

**Comment by antonybudianto** [comment]
I also considered that option but then you may want to update your `index.html` manually when bundling for production

**Comment by antonybudianto** [comment]
After reading transpiling thing in [here](https://angular.io/docs/ts/latest/quickstart.html) I decided to leave it as it's for now, if there's a better way to do it, I'll update it. Thank you
