### ISSUE TITLE
Unhandled 'error' on e2e command

### ISSUE THREAD

**Issue by padamshrestha** [antonybudianto/angular2-starter#30]
[19:59:25] Starting 'e2e-test'...
[19:59:25] Finished 'e2e-test' after 2.85 ms
[19:59:25] Starting 'e2e'...
[19:59:26] Finished 'e2e' after 6.16 µs
Starting selenium standalone server...
[launcher] Running 1 instances of WebDriver
[launcher] Process exited with error code 1
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: spawn java ENOENT
    at exports._errnoException (util.js:856:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:475:9)
    at process._tickCallback (node.js:389:17)
 Error running E2E testing

Running:
------------
Node: v5.6.0
npm: 3.4.1

**Comment by antonybudianto** [comment]
hello, have you started the local server (`gulp serve-dev`)?
the default e2e target is `localhost:3000` where the local server listens

**Comment by padamshrestha** [comment]
Yup, I started gulp serve-dev before e2e. It's listening to http://127.0.0.1:3000 and tried e2e on different console. Still having issue.

**Comment by antonybudianto** [comment]
here is my log
```
Starting selenium standalone server...
[launcher] Running 1 instances of WebDriver
Selenium standalone server started at http://192.168.1.100:65073/wd/hub
Started
.


1 spec, 0 failures
Finished in 3.492 seconds
Shutting down selenium standalone server.
[launcher] 0 instance(s) of WebDriver still running
[launcher] chrome #1 passed
```

i think a frequent issue in here is no internet connection, timeout, such thing can fail the selenium server
