### ISSUE TITLE
Couldn't find any of the tags

### ISSUE THREAD

**Issue by padamshrestha** [antonybudianto/angular2-starter#31]
Failed to inject refresh script! Couldn't find any of the tags  [ </body>, </svg> ] from C:\Projects\..\app\app.html
C:\Projects\..\app\navbar\navbar.html
C:\Projects\..\app\home\home.html

**Comment by antonybudianto** [comment]
it should be related to [this](https://github.com/tapio/live-server/issues/85)

**Comment by padamshrestha** [comment]
Yup it fixed with "live-server": "~0.9.2" and logLevel: 0

    var liveServer = {
        dev: {
            port: 3000,
            host: "127.0.0.1",
            open: '/',
            file: "index.html",
            wait: 1000,
            logLevel: 0
        },
        prod: {
            port: 3001,
            host: "127.0.0.1",
            root: 'build/',
            file: "index.html",
            wait: 1000,
            logLevel: 0
        }
    };
