### ISSUE TITLE
Inlining Component's HTML and CSS

### ISSUE THREAD

**Issue by BendingBender** [antonybudianto/angular2-starter#49]
Hello,

I was looking for a way to integrate inlining of HTML and CSS resouces into a component declaration. So that code like this:
```js
@Component({
    selector: 'navbar',
    templateUrl: 'app/navbar/navbar.html',
    styleUrls: [
        'app/navbar/navbar.css'
    ]
    directives: [RouterLink, CORE_DIRECTIVES]
})
```

will become something like this:
```js
@Component({
    selector: 'navbar',
    template: `<inline HTML here>`,
    styles: [
        `inline-css-here {}`
    ]
    directives: [RouterLink, CORE_DIRECTIVES]
})
```

Ideally without breaking typescript sourcemaps and in a perfect world so that CSS sourcemaps are imported as well. Any ideas?

**Comment by antonybudianto** [comment]
you can try [this](https://github.com/ludohenin/gulp-inline-ng2-template)
