### ISSUE TITLE
Jasmine errors on tsling

### ISSUE THREAD

**Issue by talmog** [antonybudianto/angular2-starter#53]
## Issue Overview
Hi Antony,
I have a problem when I run gulp test, I am getting this error:
` node_modules/angular2/src/testing/matchers.d.ts(4,37): error TS2503: Cannot find namespace 'jasmine'
node_modules/angular2/src/testing/testing_internal.d.ts(39,47): error TS2503: Cannot find namespace 'jasmine'
`

which I assume is the origin of about 1000 errors such as

`error TS2339: Property 'toHaveBeenCalled' does not exist on type 'NgMatchers'.
 error TS2339: Property 'toBeFalsy' does not exist on type 'NgMatchers'.`

Am I missing anything on karma.conf?
Thanks you so much!

## Information
|                      	|                                 	|
|---------------------	|---------------------------------	|
| **Operating System** 	| OSX 	|
| **Node version**     	| 5.2   	|
| **NPM Version**      	| 3.5.3    	|
| **Environment**       | Browser/Mobile/WebWorker          |

**Comment by antonybudianto** [comment]
Hi, can you remove the `typings` folder and run `typings install` again?

**Comment by talmog** [comment]
hi,
that didn't solve the problem.
Tomer

**Comment by antonybudianto** [comment]
Hmm, it's weird, it works on CI and my machine, is it a fresh clone?

**Comment by antonybudianto** [comment]
it's similar to this [issue](https://github.com/antonybudianto/angular2-starter/issues/46)

**Comment by talmog** [comment]
Ok, I think I just solved it.
On tasks/typesciprt.js
line 70 I changed 
from
`var allFiles = [].concat(files, typingFiles);`
to
`var allFiles = [].concat(typingFiles, files);`

And that seemed to get rid of all these errors.
Thank you!
