### ISSUE TITLE
Build file size

### ISSUE THREAD

**Issue by talmog** [antonybudianto/angular2-starter#57]
Hi again Antony,

## Issue Overview
In my project, `gulp build` creates two files, bundle.js and boot.js with file sizes 1.1MB and 1.6MB respectively.  
It seems very big. granted, I have a decent size project, but nothing close to 2.7 MB of javascript.

Is there a way to make the files smaller?
Are things included only once?
Does it bundle my spec.ts files?

Thanks,
Tomer

**Comment by talmog** [comment]
An interesting article related to this issue:
http://blog.jhades.org/how-to-run-angular-2-in-production-today/

**Comment by antonybudianto** [comment]
This is angular2's [issue](https://github.com/angular/angular/issues/6380)
I'll update the starter if it's already resolved, thanks.

**Comment by talmog** [comment]
Thank you!
