### ISSUE TITLE
ENOENT SystemJS

### ISSUE THREAD

**Issue by khwerhahn** [antonybudianto/angular2-starter#59]
## Issue Overview
System JS Builder Issue - `ENOENT` error

## Issue Description
I have used this starter together with [featherjs](https://github.com/feathersjs/feathers), but I cannot get the System.js builder to work. It always throws an `ENOENT` error. For some reason it doesn't find the `main` file and throws an error. When I add the `.js` to it, it throws the next error `cannot find app.component`.

I've hit a wall. Could somebody maybe help me find the error. 

## Reproducables
[Repo](https://github.com/khwerhahn/feathersng2)
The app code is hosted in the `client` folder and the build code is hosted in `public`. Everything else stays the same.

**Comment by antonybudianto** [comment]
Try to register the package name [here](https://github.com/khwerhahn/feathersng2/blob/master/systemjs.conf.js#L9)

**Comment by khwerhahn** [comment]
You mean feathers? I'm sure that this is not the problem. I basically didn't change anything from your starter, except a slightly changed directory structure. I don't understand why this is causing trouble, since I updated the gulp.config.js accordingly and everything else works fine.

**Comment by antonybudianto** [comment]
I don't use feathers myself so I can't really help on that
Does the error came only when you use feathers? @khwerhahn 
I believe the directory structure change is the problem here, and since `gulp build` will also trigger a test, then maybe the path need to be updated

**Comment by khwerhahn** [comment]
@antonybudianto thank you very much indeed! I appreciate it very much.

**Comment by antonybudianto** [comment]
@khwerhahn  You're welcome, good luck with you repo! :+1:
