### ISSUE TITLE
Using bootstrap-sass

### ISSUE THREAD

**Issue by kennyhyun** [antonybudianto/angular2-starter#64]
Hello,

Thank you for your awesome starter.

I wanted to use sass version of Bootstrap and Bootswatch because I wanted to customize like `$font-size-base`.

I have tested changing `bootswatch-dist` into `bootswatch` and `bootstrap-sass`. 
I am happy with that now.

You build an awesome starter with Sass and Bootswatch, but Bootstrap could not be customized.
Do you think is it a good idea to replace bootswatch-dist like that?

Cheers!

Kenny

**Comment by antonybudianto** [comment]
you can always replace them as it's needed, as long as it's installed via bower, so it can be wiredep-ed and bundled.

**Comment by kennyhyun** [comment]
Of course via bower.
BTW, Do you mean I can replace and pull-request or just for my case only?
I was just not sure about how it is meaningful to change your project.
(I'd be happy to make a pull-request)

**Comment by antonybudianto** [comment]
Sure, since the current setup can not be customized, I'd gladly to accept your PR :smiley:
