### ISSUE TITLE
Cannot find module 'lodash'

### ISSUE THREAD

**Issue by nmorado** [antonybudianto/angular2-starter#67]
<Have you checked issues section which may have your similar issue?>
<Please take your time filling these required information for posting issue>

## Issue Overview
gulp couldn't find lodash module while running gulp.

## Issue Description
gulp couldn't find loads module while running gulp. getting the below error while running gulp:

`app/todolist/completed-filter.pipe.ts(3,15): error TS2307: Cannot find module 'loads'.`

lodash seems installed and in the node_modules directory.

i tried deleting node_modules directory a couple of times including npm cache clean - but all to naught.

## Reproducibles
Follow the install/build instruction in the README

## Information
|                      	|                                 	|
|---------------------	|---------------------------------	|
| **Operating System** 	| OSX 10.11.4 	|
| **Node version**     	| 5.10.1   	|
| **NPM Version**      	| 3.8.3    	|
| **Environment**       | N/A          |

**Comment by antonybudianto** [comment]
can you run
```
typings install
```
?

**Comment by nmorado** [comment]
worked! worth adding it somewhere i guess...

thanks

**Comment by antonybudianto** [comment]
ok, it's weird though because it should be installed after post-install, thanks for the report
