### ISSUE TITLE
best practice in defining global deps

### ISSUE THREAD

**Issue by nmorado** [antonybudianto/angular2-starter#68]
<Have you checked issues section which may have your similar issue?>
<Please take your time filling these required information for posting issue>

## Issue Overview
I am trying to add Tether (required by Bootstrap 4) - but is not getting picked up in the build.

## Issue Description
I am trying to add Tether (required by Bootstrap 4) - but is not getting picked up in the build. This is probably a SystemJS question, but wondering if the starter app has this covered.  

## Reproducables
<Please explain the way to reproduce your issue, or even better with Plunker link>

## Information
|                      	|                                 	|
|---------------------	|---------------------------------	|
| **Operating System** 	| N/A 	|
| **Node version**     	| N/A   	|
| **NPM Version**      	| N/A    	|
| **Environment**       | N/A          |

**Comment by antonybudianto** [comment]
do you mean this [tether](https://github.com/HubSpot/tether)?
they support bower package so it can be build using `useref`
but if you use the npm package, you need to register it [here](https://github.com/antonybudianto/angular2-starter/blob/master/systemjs.conf.js#L6), and import them in ts file (and yes, you need to install its typings too)

**Comment by nmorado** [comment]
bower it is. thanks
