### ISSUE TITLE
IE11

### ISSUE THREAD

**Issue by cah-chaitanyamunagala** [antonybudianto/angular2-starter#69]
<Have you checked issues section which may have your similar issue?> Yes
<Please take your time filling these required information for posting issue>

## Issue Overview
IE 11 Rendering

## Issue Description
Can someone help me understand how to make this run on IE11? I tried adding ES6-Shim and shims-for-IE but it doesn't seem to work.

Thanks in advance.

## Reproducables
Run the app on IE11.

## Information
|                      	|                                 	|
|---------------------	|---------------------------------	|
| **Operating System** 	| Windows/OSX/Ubuntu/orYourOSHere 	|
| **Node version**     	| 4.x/5.x/orYourNodeVersionHere   	|
| **NPM Version**      	| 2.x/3.x/orYourNPMVersionHere    	|
| **Environment**       | Browser/Mobile/WebWorker          |

**Comment by antonybudianto** [comment]
put these in index.html (you can find these in angular2 official site)
```
<!-- IE required polyfills, in this exact order -->
    <script src="node_modules/es6-shim/es6-shim.min.js"></script>
    <script src="node_modules/systemjs/dist/system-polyfills.js"></script>
    <script src="node_modules/angular2/es6/dev/src/testing/shims_for_IE.js"></script>   
```

**Comment by cah-chaitanyamunagala** [comment]
Thanks for the lightening quick response. When I do what you mentioned I see the following error in IE11.

SCRIPT5078: Cannot redefine non-configurable property 'Reflect'
File: bundle-da95d59f6c.js, Line: 4, Column: 27667

Right now I am going down to lower versions of Angular2/es6-shim and zone to see if it's the version issue.

If you already know about this error, can you please let me know?

Thanks

**Comment by antonybudianto** [comment]
Here is the [issue](https://github.com/angular/angular/issues/6706)

**Comment by cah-chaitanyamunagala** [comment]
Thanks for quick responses. 

So should I bundle them differently? One for everything and one for es6-shim. Once bundled the order in which they are included matters right?

**Comment by antonybudianto** [comment]
The order matters, and polyfills should be bundled with useref, not SystemJS
