### ISSUE TITLE
The bundled result of `gulp build` is not running of Safari.

### ISSUE THREAD

**Issue by talmog** [antonybudianto/angular2-starter#76]
Hi Antony,

## Issue Overview
The bundled result of `gulp build` is not running of Safari.
Gulp build bundle.js generates an error on Safari

## Reproducables
Steps to reproduce:
- Use a fresh install of the starter
- run gulp build
- load build/index.html (via server or any other way) with Safari
- view Error:
`TypeError: Attempting to configurable attribute of unconfigurable property.` and
`ReferenceError: Can't find variable: System`
- As a result the app is not loading.

I believe it is related to es-shim, but I am not sure.

## Information
|                      	|                                 	|
|---------------------	|---------------------------------	|
| **Operating System** 	| OSX 	|
| **Node version**     	| 5.2   	|
| **NPM Version**      	| 3.5.3    	|
| **Environment**       | Safari          |

We are building a large size app using your great starter and this is crucial for us!!!
Thank you so much
Tomer

**Comment by antonybudianto7** [comment]
Hi, did it only happen using Safari? how about other browsers?
you can try [SystemJS polyfills here](https://github.com/systemjs/systemjs#promise-polyfill)
By the way I'm going to switch to SFX build (no systemjs in bundle) soon, can you try the `sfx-build-2` branch and test against Safari?

Thanks for the report.

**Comment by talmog** [comment]
Thank you for your prompt response.
The error does happen only in Safari.
SystemJS polyfills are not solving the problem here.
Also the new SFX branch has the same error and an additional one:
`reflect-metadata shim is required when using class decorators`

**Comment by talmog** [comment]
By the way, it was working until beta.17

**Comment by kennyhyun** [comment]
I don't know much about the reason but this might work.
I have inserted two js in the `index.html` right before `System.import`

    <script src="node_modules/es6-shim/es6-shim.min.js"></script>
    <script src="node_modules/angular2/es6/dev/src/testing/shims_for_IE.js"></script>

**Comment by talmog** [comment]
Is node_modules/angular2 folder there? isn't it now node_modules/@angular?

**Comment by kennyhyun** [comment]
Sorry, I haven't tried rc1 yet. but you can do similar things.

**Comment by talmog** [comment]
I'll give it a try

**Comment by talmog** [comment]
Still getting the same error :(

**Comment by antonybudianto7** [comment]
how about `gulp serve-dev`? is it only not working when bundled?

**Comment by talmog** [comment]
`gulp serve-dev` works fine on Safari. it is the bundle that breaks.
Es6-promise didn't help either. I also tried es6-sham, es5-shim and es5-sham.
I tried the angular-cli new tool and it's build does run on safari. I really don't want to migrate the project there, and rather just find a solution for this problem with your starter.

**Comment by antonybudianto** [comment]
okay, can you try to turn off either `minify` or `mangle` option in `gulp.config.js` file?

**Comment by talmog** [comment]
I tried it before, just tried it again. no success.

**Comment by antonybudianto** [comment]
I get it working by removing
```html
<script src="node_modules/es6-shim/es6-shim.min.js"></script>
```

**Comment by talmog** [comment]
but then you get many other errors...

**Comment by antonybudianto** [comment]
what kind of error did you get? 
I used `sfx-build-2` branch and just comment out es6-shim part in index, then serve build it, it run well on Safari Version 9.0 (11601.1.56)

**Comment by talmog** [comment]
When you remove the es6-shim, then the regular un-bundled version doesn't load (on sfx-build-2). 
Also I get the same error when I build.
For my project also the bundled version generates many other errors if I don't include the es6-shim.

Sorry, this is a hard one!

**Comment by antonybudianto** [comment]
Sorry, cannot help much without details.

**Comment by dottodot** [comment]
I have the same issue. With these included

```
  <script src="node_modules/es6-shim/es6-shim.min.js"></script>
  <script src="node_modules/zone.js/dist/zone.js"></script>
  <script src="node_modules/reflect-metadata/Reflect.js"></script>
  <script src="node_modules/systemjs/dist/system.js"></script>
```
serve-dev works in all browsers, however serve-build breaks things in Safari and IE. If I remove es6-shim Safari works fine but IE is broken with the error

```
cannot redefine non-configurable property 'Reflect'
```

**Comment by antonybudianto7** [comment]
Feel free to open PR if you have a fix for this, thank you

**Comment by dottodot** [comment]
The only way I can get it to work is too not bundle those scripts so it must be something to do with systemjs-builder but no idea what.

**Comment by kennyhyun** [comment]
I checked out rc1 and the issue today. 
When I tested removing `es6-shim` from bundle.js and add it manually in the build directory, the error was gone.
Uglifying `es6-shim` might have a problem. and 0.35.1 was the same.

Anyway, from this idea, I adjusted es6-shim's position after `system.js` and used `es6-shim.js` instead of `es6-shim.min.js`. This was a solution.

    
    <script src="node_modules/zone.js/dist/zone.js"></script>
    <script src="node_modules/reflect-metadata/Reflect.js"></script>
    <script src="node_modules/systemjs/dist/system.js"></script>

    
    <script src="node_modules/es6-shim/es6-shim.js"></script>
    


I'll PR this soon.

**Comment by antonybudianto** [comment]
wow, it's great @kennyhyun , I look forward to it 👍

**Comment by antonybudianto** [comment]
@talmog, can you confirm the fix?

**Comment by dottodot** [comment]
Works for me.

**Comment by talmog** [comment]
confirmed! thank you!
