### ISSUE TITLE
Compiling files to dist or build directory

### ISSUE THREAD

**Issue by haxoza** [antonybudianto/angular2-starter#77]
Having `*.js` and `*.js.map` files just next to `*.ts` sources is painful in navigating through the files during development. It would be great to keep compiled files in a different directory.

For example this kind of solution was applied for coffee script sources in [Angular1 Gulp Generator](https://github.com/Swiip/generator-gulp-angular) and it worked great. Please let us know if you agree with such solution. Eventually some pull request could be submitted.

I believe the motivation behind this issue is the same as in #22.

**Comment by antonybudianto** [comment]
I'm okay as long as it still fits with the workflow, please send the pull request 👍

**Comment by antonybudianto** [comment]
I've committed to the sfx PR, please try and review, thanks

**Comment by haxoza** [comment]
@antonybudianto thanks for your super quick reaction!

I've fetched pull request, tested it and it seems to work great. I think it can be merged to master.

**Comment by antonybudianto** [comment]
Thanks, I'll merge it soon after through checks
