### ISSUE TITLE
Error is coming when running karma start

### ISSUE THREAD

**Issue by asvifi85** [antonybudianto/angular2-starter#8]
Throwing error on karma start.
No provider for logger service.

![jasmineerror2](https://cloud.githubusercontent.com/assets/5996806/12073428/f62d1a88-b146-11e5-8428-3d68d7e4ce37.png)

**Comment by antonybudianto** [comment]
thank you for the report, i will take a look at that

**Comment by antonybudianto** [comment]
how about running `gulp test`? @asvifi85
