### ISSUE TITLE
Support for barrels?

### ISSUE THREAD

**Issue by finleysg** [antonybudianto/angular2-starter#82]
## Issue Overview
Weird issue when trying to use barrels.

## Issue Description
I've forked your starter and updated the styles to use my LESS files. Site comes up fine.

Now I've replaced the navbar component with my own header component, and I've moved the logger into a shared folder with a few of my own common components. In both of those cases, I've used an index.ts file to create a barrel (I'm trying to follow the [style guide](https://angular.io/styleguide).

The site recompiles with no errors, but I'm getting a pair of 404s now in the browser:

* /tmp/app/header.js
* /tmp/app/shared.js

I can't figure out why or where these urls are being generated -- too much typescript magic for me since I'm new to .ts. Is there a missing configuration to support using barrels?

## Information
|                      	|                                 	|
|---------------------	|---------------------------------	|
| **Operating System** 	| Arch Linux 4.5.2 |
| **Node version**     	| 6.2.0 |
| **NPM Version**      	| 3.9.2 |
| **Environment**       | Browser |

**Comment by finleysg** [comment]
Ah - it was a system js configuration I was missing. Needed to add to the packages in system.conf.js:

    var packageNames = [
        '@angular/common',
        '@angular/compiler',
        '@angular/core',
        '@angular/http',
        '@angular/platform-browser',
        '@angular/platform-browser-dynamic',
        '@angular/router',
        '@angular/testing',
        'lodash',
        'app/shared',
        'app/header',
        'app/header/shared'
    ];

**Comment by antonybudianto** [comment]
@finleysg , yes you need to register them there or you must put suffix like 
```ts
import {any} from 'app/shared/index'
```
of course i prefer registering them first
