### ISSUE TITLE
 npm ERR! Windows_NT 6.1.7601 npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "ins npm ERR! node v0.12.0 npm ERR! npm  v2.5.1 npm ERR! code EPEERINVALID  npm ERR! peerinvalid The package es6-shim does not satisfy its siblings' peerDependencies requirements! npm ERR! peerinvalid Peer angular2@2.0.0-beta.6 wants es6-shim@^0.33.3

### ISSUE THREAD

**Issue by kumartarun** [antonybudianto/angular2-starter#98]
`<GitHub` issues are only for bug reports and feature requests,
question, support, or help can be send to Stackoverflow>
<Have you checked issues section which may have your similar issue?>
<Please take your time filling these required information for posting issue>

## Issue Overview
Not able to run this due to dependency 

## Issue Description
 npm ERR! Windows_NT 6.1.7601 npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "ins npm ERR! node v0.12.0 npm ERR! npm  v2.5.1 npm ERR! code EPEERINVALID  npm ERR! peerinvalid The package es6-shim does not satisfy its siblings' peerDependencies requirements! npm ERR! peerinvalid Peer angular2@2.0.0-beta.6 wants es6-shim@^0.33.3

## Reproducables
<Please explain the way to reproduce your issue, or even better with Plunker link>

## Information
|                      	|                                 	|
|---------------------	|---------------------------------	|
| **Operating System** 	| Windows/OSX/Ubuntu/orYourOSHere 	|
| **Node version**     	| 4.x/5.x/orYourNodeVersionHere   	|
| **NPM Version**      	| 2.x/3.x/orYourNPMVersionHere    	|
| **Environment**       | Browser/Mobile/WebWorker          |

**Comment by antonybudianto7** [comment]
Please use latest starter since Angular is already out of beta, thanks

**Comment by kumartarun** [comment]
```
npm ERR! peerinvalid The package reflect-metadata does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer angular2@2.0.0-beta.6 wants reflect-metadata@0.1.2
npm ERR! peerinvalid Peer angular2-in-memory-web-api@0.0.11 wants reflect-metadata@^0.1.3
```
This is not related to Node getting this in latest code from 2.0.0-rc.1 version 
Please give me some working example using 2.0.0-rc.1 version with system JS i am getting this issue everywhere ...

**Comment by antonybudianto7** [comment]
no, the latest version didn't have **beta.6** as dependency
