### ISSUE TITLE
On spec files changes unit test are not running/reloading

### ISSUE THREAD

**Issue by darxx** [antonybudianto/angular2-starter#99]
Continues code developing process is not effective. On spec changes need to stop server and start over. No feat back from unit test on refactoring/changing code.

## Issue Overview
On code/template changes or spec changes unit test are not "reloader"

## Issue Description
<Please explain the issue in details>
On spec.js changes unit test are not reloading.
On .html changes unit test are not reloading.
On code .ts changes unit test are not reloading.

## Reproducables
gulp

## Information
|                      	|                                 	|
|---------------------	|---------------------------------	|
| **Operating System** 	| Windows/OSX/Ubuntu/orYourOSHere 	|
| **Node version**     	| 4.x/5.x/orYourNodeVersionHere   	|
| **NPM Version**      	| 2.x/3.x/orYourNPMVersionHere    	|
| **Environment**       | Browser/Mobile/WebWorker          |

**Comment by antonybudianto7** [comment]
try
```bash
gulp test -w
```

**Comment by darxx** [comment]
Is it included in documentation?

**Comment by antonybudianto7** [comment]
https://github.com/antonybudianto/angular2-starter/wiki/Gulp-Tasks#test

also in 
https://github.com/antonybudianto/angular2-starter/releases

**Comment by darxx** [comment]
Browser sync is not active after this command.

**Comment by darxx** [comment]
Server is not started.

**Comment by antonybudianto7** [comment]
what are the error traces?

**Comment by darxx** [comment]
after gulp test -w
http://localhost:3000/
http://prntscr.com/bfquzn

**Comment by antonybudianto7** [comment]
maybe it's because there's already a watch in test -w, but you run serve-dev again which contains watches (sass, ts)

**Comment by antonybudianto7** [comment]
looks like you're not supposed to run `gulp test -w` and `gulp serve-dev` together

**Comment by darxx** [comment]
So in case of gulp test -w and gulp serve-dev running in the same time http://screencast.com/t/UClqJWTsVD
http://screencast.com/t/M8NJZDuFju

**Comment by darxx** [comment]
How I can run server and unit test together?

**Comment by darxx** [comment]
Or single is it gulp task for this case?

**Comment by antonybudianto7** [comment]
I don't think it's possible now

**Comment by darxx** [comment]
Thus it remains a proposal for the future.

**Comment by antonybudianto7** [comment]
Of course, any help will be nice

**Comment by darxx** [comment]
Thank You.

**Comment by antonybudianto7** [comment]
actually you can run `gulp serve-dev` / `gulp` first, then do `gulp test -w` and no errors raised. doing it vice versa will cause error because `gulp serve-dev` will cleanup all things and the test watch will be triggered because of that
